---
tunnel: ${SECRET_CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/cred.json
originRequest: # Top-level configuration
  connectTimeout: 30s

ingress:
  - hostname: hashivault.${SECRET_DOMAIN}
    service: https://istio-gateway.istio-ingress.svc.cluster.local
    originRequest:
      noTLSVerify: true
  - hostname: id.${SECRET_DOMAIN}
    service: https://istio-gateway.istio-ingress.svc.cluster.local
    originRequest:
      noTLSVerify: true
  - service: http_status:404
