# yamllint disable
apiVersion: v1
stringData:
    cred.json: ENC[AES256_GCM,data:Xp0FgPz6zN3WDyapaMKQiJOaD9Ku99QJ8bvPhvx86x1TKNqRciPDawX9cZ9b7ShV/JwBvcwO9uA+FbU40IlRcTUXKAYFWTL3+58doR566RnDsBmAnwif26LrEUN0jhQXO/YxYmwLCiS6IOjU3j0mYo5Xwu4+JttGKp6eANnYzVGwdYyMYSMl7gRWGDAq+0SDxMJh2vFXVe8L0rQ62qqOCXo=,iv:7Pu+5F4rAkZsWedyywO+Iwu6Wa6kxx/69uktlvEWKW4=,tag:Y55mA0Z6OlbC66XkmyIOoA==,type:str]
kind: Secret
metadata:
    name: tunnel-creds
    namespace: networking
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-28T03:21:26Z"
    mac: ENC[AES256_GCM,data:JjhEv1vMM7Q+ZXOVC1pgeX40VdrSuSANZbCmTkVNlSe0uxJsJYtMQiahjJFWkwqfWYYOq9Aen//J+qShLySPBdXAquY/0XUCr2jP0FhGuSJ8FKPzXuEYYNCzaqfg7ohtvVkTM0FKp53zra0P7G4+DxbopCTqxWJC/FNIZXEJMzI=,iv:T6C0LKYNb6yAFWpwyKJMYUd6rdqHcU8tdJ2fTrb94Ds=,tag:QfhnP7BmsSbbG2iV0/gE/A==,type:str]
    pgp:
        - created_at: "2023-02-26T05:12:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQARAApzuMqdsd2qdpkK8aldJ8HabacGlB96h5icPpn5MvhFBc
            tDUgzJMZaDKg3RhTvjwYNaFiIQ6Bq+wLXHqziG3YcJd9+CkggF/hqkeekX2J10VB
            9BOzU/4NcdcEcHPzXnffMxWJe8h7be4mb4ptCv7TrYVOd1aJ3skeBNZIwFLX39OQ
            hNi7S2SoUbLgCHr8uYJuYZCvim0EIHgtvtuGLZ/WC38BR6shAc0zPaERQxTpqinu
            KpOtVLg/rX+LBZErvmlI6LBBawSZcVrAMuKdgjDleWXLdajBjp5uRGVM7vgzPwQE
            4NHdOlyd8EMVYZVlbUsKP467vVjoggL4TVoYoqUP9liNBzc+g1vVobupqqbh+xy3
            +7NXNHru6E+yyGbQvHnVByYqsj7iiwYQI9PwscpTjZ8sjdW5ZfPoXNkbGg3RCSAS
            f5zAlvPGQQMZqCAK9XEP3yAXtIRZ6b0cGb4gRIq1W43gAHt8GaM80EJlHWg6vzG6
            4/trJYelFGD/RloZU66LJpHYPyWzXF08bdTMJZxdRw4xw1rAXB3B74GELc/761uh
            4Xh7ZzhgQ8eGNPEalKVHNoSdNr+1has64pv4pyxRmxcaEz8KeXubqmRdo+Xyl8Xe
            gHbrJvookFuxibZe9x9cJJ0REjbyXlbNL3k4nOxhMame9th62kle2uQ3CVGEgJvU
            aAEJAhA1vw7L8n4uqYA1GDCC4CqpW13X+pF74Dvt2tMg2pgiyrKDl527iyjsZNaN
            Z9aMTTewAHqclulzRofeB4/T3X3t3gerNmp14h/Ic7M/FuumAdqJv238NzvAR2Hx
            J/2I8woFmHtg
            =+Wh3
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
        - created_at: "2023-02-26T05:12:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9Qs/eFVrZ++AQ//a8WrgDQmUuMaSJL1xu6Yyi/w1Z5Xsu7SI/M1oP8F3IvD
            GlR+RlfF8/aBdn1GtcHwTqW1G//X3x5D/OOQJkqD0xLu1ZFsERPIJeOjl8Cgtuma
            exthq4DEbdlsGX0fy7JXHoECOQmQXFHsTcGNGDYGaRbeSSG5ei0+P73NuLqoRheI
            zKT4z96q0SxptiyCvAB4Qtbz1IQGEN8ntcMnIXPT2o7RWJsP76lBEVmJZ73k+ugg
            kelZ2OyeU9OeaNuQLFx2+jreoUZsZxe5Fc4wWtO9kAiOynOYl5FUpOJETL9fczIx
            SEMUbDn3t6dbs74u16xZdSh+swh5HFGKmoVJiJAkZzq5pQ8Go7ycOCwyKIptoRII
            zWmrn64+CK8DJq0LQAA91r1xerl7O1pEHhdk8ltJseBnMpdxeoraJadCIon+pKMZ
            4IGe4gGiNt2k+QIhYe9SppxAvwkik9i/ghenJ8seANDL5Il1mV+/Vb7rHzLiraTI
            MvJkWttH0NPIxLOOdrXr19YwmI/9TaX3sxfZQ4XILzo0OLYTPV97Is2pxFyq0nwy
            OHqiEExuF5MnBtYV31qvHfHOm9hdz0GTcbALZJnWisuw998JfP/vbwDAuBb8Ep9j
            E60+anG9H2XYTTEBqcB2kPUB8ErY/B7dMVGGMV9pYUBsvCZBJ8LWf9Z7W9oX2MLS
            UQH/LI4euwPoFbcl2IZOseV+KSa2f8jYec7ZzScGwn7uRCC+IBDUpeFCrMKN91vT
            76lMLhnoDBEvjfJAfWI3tlH+DY/Y7htWhxmOTKSraqtUiA==
            =4MfT
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
