---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: hashivault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: 0.24.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp-charts
        namespace: flux-system
  values:
    metrics:
      enabled: true
    service:
      enabled: true
    server:
      extraLabels:
        configmap.reloader.stakater.com/reload: vault-config
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/icon: shield-key
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host hashivault.${SECRET_DOMAIN}
            paths:
              - /
        tls:
          - secretName: vault-tls
            hosts:
              - *host
      dataStorage:
        enabled: true
        size: 5Gi
        storageClass: local-path
      auditStorage:
        enabled: true
        size: 5Gi
        storageClass: local-path
      # extraSecretEnvironmentVars is a list of extra environment variables to set with the stateful set.
      # These variables take value from existing Secret objects.
      extraSecretEnvironmentVars:
        - envName: VAULT_OCIKMS_SEAL_KEY_ID
          secretName: vault
          secretKey: VAULT_OCIKMS_SEAL_KEY_ID
        - envName: VAULT_OCIKMS_CRYPTO_ENDPOINT
          secretName: vault
          secretKey: VAULT_OCIKMS_CRYPTO_ENDPOINT
        - envName: VAULT_OCIKMS_MANAGEMENT_ENDPOINT
          secretName: vault
          secretKey: VAULT_OCIKMS_MANAGEMENT_ENDPOINT
        - envName: VAULT_TOKEN
          secretName: vault
          secretKey: VAULT_TOKEN
      extraEnvironmentVars:
        TZ: ${TIMEZONE}
        VAULT_SEAL_TYPE: ocikms
        VAULT_ADDR: "http://127.0.0.1:8200"
      # extraVolumes:
      #   - type: secret
      #     name: kms-vault-unseal
      #     path: /vault/userconfig
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 1024Mi
      standalone:
        enabled: true
        config: |
          ui = true
          storage "file" {
            path = "/vault/data"
          }
          # seal "ocikms" {
          #     auth_type_api_key    = "true"
          # }
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            telemetry {
              unauthenticated_metrics_access = "true"
            }
          }
          telemetry {
            prometheus_retention_time = "24h",
            disable_hostname = true
          }
          # service_registration "kubernetes" {}
    ui:
      enabled: true
    csi:
      enabled: false
    injector:
      enabled: "true"
