---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - vaultwarden-config-pvc.yaml
  - vaultwarden-backup-pvc.yaml
  - secret.sops.yaml
  - vw-backup-cronjob.yaml