---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-backup
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path