---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - kube-system
  - networking
  - hashivault/ks.yaml
  - hashivault/namespace.yaml
  # - gitlab
  # - vaultwarden/ks.yaml
  # - vaultwarden/namespace.yaml
