---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    goldilocks.fairwinds.com/enabled: "true"
  annotations:
    istio-injection: enabled
    kustomize.toolkit.fluxcd.io/prune: disabled
    # "cni.projectcalico.org/ipv4pools": "[\"lb-pool\"]"